name: "My First github actions module"

on:
  workflow_call:
    inputs:
      artifact_nae:
        type: string
        required: false
        default: apiapp
  
jobs:
  release:
      name: Release Apps
      needs: build

      runs-on: ubuntu-latest

      steps:
      - name: Download FunctionApp artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifact_name }}
          path: artifacts/api

      - name: Zip FunctionApp artifact
        shell: bash
        run: |
          pushd artifacts/api
          zip -qq -r ${{ inputs.artifcat_name }}.zip .
          popd

          mv artifacts/api/${{ inputs.artifact_name }}.zip artifacts/${{ inputs.artifact_name }}.zip

      - name: Release FunctionApp artifact to GitHub
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            artifacts/${{ inputs.artifact_name }}.zip  