name: "My first github action"

on: push

env:
  WORKFLOW_LEVEL: "THIS VALUE COMES FROM THE WORKFLOW LEVEL"

jobs:
  first-job: 
    name: "first job"


    strategy:
      matrix:
        os: [ 'windows-latest', 'macos-latest', 'ubuntu-latest']
        nodejs: ['14.x', '16.x']

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: output value from ${{ matrix.os }}
        id: first
        shell: bash
        run:
          first_value="this is the first value"

          echo "OS ${{ matrix.os }}"
          echo "nodejs ${{ matrix.nodejs }}"