name: "My first github action"

on: [ 'push', 'pull_request' ]

jobs:
  first-job:
    name: "first job"


    strategy:
      matrix:
        os: [ 'windows-latest', 'macos-latest', 'ubuntu-latest']
        nodejs: ['14.x', '16.x']

    runs-on: ${{ matrix.os }}
    
    steps:

      - name : Steup node.js
        uses: actions/setup-node@v3

      - name: output value from ${{ matrix.os }}
        id: first
        shell: bash
        run:
          first_value="this is the first value"

          echo "OS ${{ matrix.os }}"
          echo "nodejs ${{ matrix.nodejs }}"

  second-job:
    name: second
    needs: first-job

    runs-on: ubuntu-latest

    steps:
    
      - name : second job first step
        shell: bash
        run:
          echo second job
  third-job:
    name: third
    needs: third-job

    runs-on: ubuntu-latest

    steps:
    
      - name : third job first step
        shell: bash
        run:
          echo third job