name: "My first github action"

on: push

env:
  WORKFLOW_LEVEL: "THIS VALUE COMES FROM THE WORKFLOW LEVEL"

jobs:
  first-job: 
    name: "first job"


    runs-on: ubuntu-latest
    
    steps:
      - name: set output value
        id: first
        shell: bash
        run:
          first_value="this is the first value"

          echo "::set-output name=my_first_value::$first_value"
          
      - name: get output value
        shell: bash
        run:
          echo ${{ steps.first.outputs.my_frirst_value }}